package com.chat.chat.mapper;

import com.chat.chat.pojo.ChatMsg;
import com.chat.chat.pojo.ChatMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    long countByExample(ChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    int deleteByExample(ChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    int insert(ChatMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    int insertSelective(ChatMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    List<ChatMsg> selectByExample(ChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    ChatMsg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    int updateByExampleSelective(@Param("record") ChatMsg record, @Param("example") ChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    int updateByExample(@Param("record") ChatMsg record, @Param("example") ChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    int updateByPrimaryKeySelective(ChatMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    int updateByPrimaryKey(ChatMsg record);
}