package com.chat.chat.mapper;

import com.chat.chat.pojo.myFriends;
import com.chat.chat.pojo.myFriendsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface myFriendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    long countByExample(myFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    int deleteByExample(myFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    int insert(myFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    int insertSelective(myFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    List<myFriends> selectByExample(myFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    myFriends selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    int updateByExampleSelective(@Param("record") myFriends record, @Param("example") myFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    int updateByExample(@Param("record") myFriends record, @Param("example") myFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    int updateByPrimaryKeySelective(myFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Jan 06 15:31:00 CST 2020
     */
    int updateByPrimaryKey(myFriends record);
}