package com.chat.chat.mapper;

import com.chat.chat.pojo.myFriends;
import com.chat.chat.pojo.myFriendsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface myFriendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Dec 27 19:42:59 CST 2019
     */
    long countByExample(myFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Dec 27 19:42:59 CST 2019
     */
    int deleteByExample(myFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Dec 27 19:42:59 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Dec 27 19:42:59 CST 2019
     */
    int insert(myFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Dec 27 19:42:59 CST 2019
     */
    int insertSelective(myFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Dec 27 19:42:59 CST 2019
     */
    List<myFriends> selectByExample(myFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Dec 27 19:42:59 CST 2019
     */
    myFriends selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Dec 27 19:42:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") myFriends record, @Param("example") myFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Dec 27 19:42:59 CST 2019
     */
    int updateByExample(@Param("record") myFriends record, @Param("example") myFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Dec 27 19:42:59 CST 2019
     */
    int updateByPrimaryKeySelective(myFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Dec 27 19:42:59 CST 2019
     */
    int updateByPrimaryKey(myFriends record);
}